= OpenShift Virtualization workshop へようこそ

[%hardbreaks]
== はじめに
OpenShift Virtualization は、最新の Kubernetes ベースのインフラストラクチャ上に仮想マシンを導入することを可能にします。
また、仮想マシン、コンテナ、サーバーレス機能で構成されるアプリケーションを作成することができ、これらはすべて Kubernetes ネイティブのツールとパラダイムを使用して一緒に管理されます。

このワークショップは、Red Hat OpenShift Virtualization を実際に体験していただくために企画されました。

このイベントでは、仮想化管理者が日々のワークフローでよく遭遇する多くの一般的な管理アクティビティを体験します。

== ワークショップに参加することで最も恩恵を受けるのは誰ですか？

*仮想マシン管理者* -- OpenShift Virtualizationで仮想ゲストの日々の管理を担当している方。このようなユーザーは、仮想ゲストのプロビジョニング、ゲストとその中で実行されるアプリケーションの日々の管理を担当することが多いでしょう。

*仮想インフラストラクチャ管理者* -- OpenShift Virtualizationソリューションをホストする物理インフラストラクチャの責任者。これらのユーザーは、実行中の仮想マシンの日々の運用に影響を与える、環境に対する物理ハードウェア、ストレージ、ネットワークの変更に責任を負います。

== ワークショップでカバーされる内容は？

取り上げる主なセクションは以下の2つです:

* _仮想マシンの管理_ : このセクションでは、仮想マシンの作成や割り当てリソースの変更など、仮想マシン管理の基本について説明します。

* _既存の仮想マシンの移行_ : このセクションでは、Migration Toolkit for Virtualization (MTV) を使用して、既存の VMware vSphere 環境から OpenShift Virtualization へ仮想マシンを移行します。

== OpenShift 仮想化とは？

* OpenShift Virtualization は Red Hat OpenShift の機能です。アドオンや拡張製品ではなく、すべてのエディションに含まれています。
* 現在のすべてのOpenShiftサブスクリプション所有者は、OpenShift サブスクリプションの一部として OpenShift Virtualization を利用可能です。
OpenShift 4.5 以降より一般公開されています。
* OpenShift Virtualization は、Cloud Native Computing Foundation (CNCF) のサンドボックスプロジェクトである KubeVirt プロジェクトの上流で開発されている"container-native virtualization" の技術に基づいています。
* Red Hat Enterprise Linux KVM ハイパーバイザー（RHEL KVM）を活用します。このハイパーバイザーは、世界中の多くの組織やクラウドサービスプロバイダーで使用されており、15 年以上にわたって開発が続けられている、成熟した高性能なオープンソースハイパーバイザーです。
* OpenShift VirtualizationはRHEL KVMハイパーバイザーを活用し、VMをKubernetesとKubeVirtで管理できるようにします。OpenShift Virtualization上のVMは、Kubernetesのスケジューリング、ネットワーク、およびストレージのインフラを使用します。
* OpenShift Virtualization は、Red Hat の他の KVM 仮想化製品に適用されるのと同じ規則に従って、Windows ゲストのサポートについて Microsoft の SVVP 認証を受けています。
* OpenShift Virtualization は OpenShift が仮想マシンを OpenShift クラスタにデプロイ、管理、接続することを可能にします。これには、Kubernetes ネイティブのメソッドを使用してこれらの VM に接続して管理し、Pipelines、GitOps、Service Mesh などの OpenShift 機能を利用する機能が含まれます。

== 従来のVMプラットフォームから乗り換える理由

**クラウドネイティブ開発および/またはクラウドネイティブ運用の採用:**
Red Hat OpenShift は、スピード、俊敏性、信頼性、そして選択肢を備えたアプリケーションの構築を支援します。構築する場所を選ばず、本番モードでコードを作成できます。
顧客は、ビジネス上重要な仕事に集中できます。

**完全なアプリケーション開発スタック:**
Red Hat OpenShift Dev Spaces (旧 Red Hat CodeReady Workspaces)、ランタイム、インテグレーションとプロセス自動化、サーバーレス、パイプラインなど、全体を通してセキュリティが確保されています。

**インフラのコストをイノベーションに転換: ** 
OpenShift ネイティブ・アーキテクチャは、レガシーな SDDC (Software-Defined Data Center) の重い構造から、軽量なコンテナ・ネイティブ・フレームワークへと変化させます。

**リスクの軽減：**
OpenShiftはオンプレミスとパブリッククラウドのオプションをサポートしており、パブリッククラウドのロックインに対する保険となります。

**インフラに非依存：**
Red Hat OpenShift は、ベアメタル、オンプレミス仮想化、またはパブリッククラウド上で一貫して実行されるため、デプロイとアップデートの究極の選択肢と柔軟性が得られます。

**純粋なオープンソースのイノベーション：**
Kubernetes、サーバーレス、サービスメッシュ、Kubernetes Operators などのイノベーションは、Red Hat を筆頭とするオープンソースの開発スピードによってもたらされます。

== 次のステップ
OpenShift Virtualization の詳細をお知りになりたい方は、 https://www.redhat.com/en/technologies/cloud-computing/openshift/virtualization[ランディングページ^] をご覧になるか、 https://docs.openshift.com/container-platform/latest/virt/about_virt/about-virt.html[ドキュメント^] をご確認ください。また、 https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqeQeTosfoFzTyE_QmWZW6n_[YouTube^] でデモビデオをいくつかご覧ください。

== ラボ環境の要件

* 参加者は、ブラウザとインターネットにアクセスできる自分のコンピュータを持っている必要があります。
* Firefoxではコピー＆ペーストができないため、Chromiumベースのブラウザを推奨します。
* リモートアクセスコンソールはデフォルトで US キーボードレイアウトを使用します。特殊文字（@, &など）がどのキーで入力可能か予めご確認下さい。

== OpenShift コンソールへのログイン
OpenShift コンソールのログイン情報は、ラボ環境を払い出した際に表示されたページで確認できます。

- username: kubeadmin
- password: ラボ環境で表示されているもの

=== vCenter へのアクセス

実習ラボの移行の章では、 https://vcsnsx-vc.infra.demo.redhat.com/ui/app/search?query=bastion&searchType=simple[VMware vSphere^] 環境にログインして調べます。

ユーザー認証情報は講師より提示されます。

